Update test-results.yaml

diff --git a/.github/workflows/test-results.yaml b/.github/workflows/test-results.yaml
--- a/.github/workflows/test-results.yaml
+++ b/.github/workflows/test-results.yaml
@@ -17,61 +17,61 @@ jobs:
     with:
       type: api
 
-  merge-test-results:
-    runs-on: ubuntu-latest
-    if: always()
-    needs: [call-web-tests, call-api-tests]  # This ensures it runs after both test jobs
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
+  # merge-test-results:
+  #   runs-on: ubuntu-latest
+  #   if: always()
+  #   needs: [call-web-tests, call-api-tests]  # This ensures it runs after both test jobs
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v2
 
-      - name: "⬇️ Download Web Test Results"
-        uses: actions/download-artifact@v4
-        with:
-          name: robot-test-results-web
-          path: webapp_tests/robot-test-results
+  #     - name: "⬇️ Download Web Test Results"
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: robot-test-results-web
+  #         path: webapp_tests/robot-test-results
 
-      - name: "⬇️ Download API Test Results"
-        uses: actions/download-artifact@v4
-        with:
-          name: robot-test-results-api
-          path: webapp_tests/robot-test-results
+  #     - name: "⬇️ Download API Test Results"
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: robot-test-results-api
+  #         path: webapp_tests/robot-test-results
 
-      - name: "📜 Install Robot Framework"
-        run: pip install robotframework
+  #     - name: "📜 Install Robot Framework"
+  #       run: pip install robotframework
 
-      - name: Debug - List Test Results Directory
-        run: ls -lah webapp_tests/robot-test-results
+  #     - name: Debug - List Test Results Directory
+  #       run: ls -lah webapp_tests/robot-test-results
 
 
-      - name: Merge Test Results
-        run: |
-          if [[ -f webapp_tests/robot-test-results/api_output.xml && -f webapp_tests/robot-test-results/web_output.xml ]]; then
-            rebot --output webapp_tests/robot-test-results/output.xml \
-                  webapp_tests/robot-test-results/api_output.xml \
-                  webapp_tests/robot-test-results/web_output.xml
-          else
-            echo "❌ One or more output files are missing!"
-            ls -lah webapp_tests/robot-test-results  # Show what exists for debugging
-            exit 1  # Fail the job if results are missing
-          fi
+  #     - name: Merge Test Results
+  #       run: |
+  #         if [[ -f webapp_tests/robot-test-results/api_output.xml && -f webapp_tests/robot-test-results/web_output.xml ]]; then
+  #           rebot --output webapp_tests/robot-test-results/output.xml \
+  #                 webapp_tests/robot-test-results/api_output.xml \
+  #                 webapp_tests/robot-test-results/web_output.xml
+  #         else
+  #           echo "❌ One or more output files are missing!"
+  #           ls -lah webapp_tests/robot-test-results  # Show what exists for debugging
+  #           exit 1  # Fail the job if results are missing
+  #         fi
 
-      - name: "⬆️ Upload Merged Test Results"
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: robot-test-results
-          path: webapp_tests/robot-test-results/output.xml
+  #     - name: "⬆️ Upload Merged Test Results"
+  #       if: always()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: robot-test-results
+  #         path: webapp_tests/robot-test-results/output.xml
 
-      - name: "🐍 Run Test Results Parsing Script"
-        if: always()
-        run: python functions/display_test_results.py ./webapp_tests/robot-test-results/output.xml webapp_tests/robot-test-results/report.md all
+  #     - name: "🐍 Run Test Results Parsing Script"
+  #       if: always()
+  #       run: python functions/display_test_results.py ./webapp_tests/robot-test-results/output.xml webapp_tests/robot-test-results/report.md all
 
-      - name: "📑 Display parsed test results"
-        if: always()
-        run: |
-          if [ -f webapp_tests/robot-test-results/report.md ]; then
-            cat webapp_tests/robot-test-results/report.md >> $GITHUB_STEP_SUMMARY
-          else
-            echo "❌ Report not found!" >> $GITHUB_STEP_SUMMARY
-          fi
+  #     - name: "📑 Display parsed test results"
+  #       if: always()
+  #       run: |
+  #         if [ -f webapp_tests/robot-test-results/report.md ]; then
+  #           cat webapp_tests/robot-test-results/report.md >> $GITHUB_STEP_SUMMARY
+  #         else
+  #           echo "❌ Report not found!" >> $GITHUB_STEP_SUMMARY
+  #         fi
